import Foundation
import Testing
@testable import ToSpeech

/// Parity tests ported from `scripts/assessment/phoneticxeus/test_evidence.py`'s lattice cases —
/// `test_lattice_selects_whole_variants_against_exhaustive_viterbi`,
/// `test_repeated_phones_across_words_need_blank`,
/// `test_align_variants_accepts_per_position_options`,
/// `test_align_units_locates_pair_unit_on_single_rhotic_token` — plus a cross-check of the same
/// concrete inputs against the Task 2 golden fixture
/// `ToSpeechTests/Fixtures/XeusNative/lattice-golden.json`, which was generated by
/// `scripts/assessment/phoneticxeus/dump_golden.py` running the real Python `evidence.py`.
///
/// The exhaustive-Viterbi case pins a single concrete `lp` (the first draw of numpy
/// `default_rng(17).dirichlet`, persisted in the golden) so the Swift test has no dependency on
/// reproducing numpy RNG behavior — it replicates the comparison logic (lattice selection vs the
/// best of all 4 variant combinations by exhaustive `path` scoring) on that persisted draw.
@Suite struct XeusLatticeTests {
  // MARK: - lp construction (byte-for-byte port of Python's `self.lp` / `lp_from_rows`)

  private func lp(_ rows: [[Int: Double]], vocabSize: Int = 428, floor: Double = 1e-8) -> [[Double]] {
    rows.map { values in
      var row = [Double](repeating: floor, count: vocabSize)
      for (token, prob) in values { row[token] = prob }
      let sum = row.reduce(0, +)
      return row.map { Foundation.log($0 / sum) }
    }
  }

  // MARK: - Golden fixture loading (ToSpeechTests/Fixtures/XeusNative/lattice-golden.json)

  private func loadGoldenCases() throws -> [[String: Any]] {
    let url = URL(fileURLWithPath: #filePath)
      .deletingLastPathComponent()
      .appendingPathComponent("Fixtures/XeusNative/lattice-golden.json")
    let data = try Data(contentsOf: url)
    let json = try JSONSerialization.jsonObject(with: data) as! [String: Any]
    return json["cases"] as! [[String: Any]]
  }

  private func goldenCase(_ name: String) throws -> [String: Any] {
    let cases = try loadGoldenCases()
    guard let match = cases.first(where: { $0["name"] as? String == name }) else {
      Issue.record("golden case not found: \(name)")
      fatalError("golden case not found: \(name)")
    }
    return match
  }

  private func asDouble(_ any: Any) -> Double { (any as! NSNumber).doubleValue }
  private func asIntArray(_ any: Any) -> [Int] { (any as! [Any]).map { ($0 as! NSNumber).intValue } }
  private func asIntMatrix(_ any: Any) -> [[Int]] { (any as! [Any]).map { asIntArray($0) } }
  private func asIntCube(_ any: Any) -> [[[Int]]] { (any as! [Any]).map { asIntMatrix($0) } }

  private func asLp(_ any: Any) -> [[Double]] {
    (any as! [Any]).map { row in (row as! [Any]).map { asDouble($0) } }
  }

  private func asStringCube(_ any: Any) -> [[[String]]] {
    (any as! [Any]).map { word in (word as! [Any]).map { variant in (variant as! [Any]).map { $0 as! String } } }
  }

  private func asVocab(_ any: Any) -> [String: Int] {
    (any as! [String: Any]).mapValues { ($0 as! NSNumber).intValue }
  }

  // MARK: test_lattice_selects_whole_variants_against_exhaustive_viterbi

  @Test func latticeSelectsWholeVariantsAgainstExhaustiveViterbi() throws {
    let golden = try goldenCase("lattice_selects_whole_variants_against_exhaustive_viterbi")
    let vocab = asVocab(golden["vocab"]!)
    let phoneWords = asStringCube(golden["words"]!) // [[["b","d"],["d","b"]],[["b"],["v","d"]]]
    let matrix = asLp(golden["lp"]!)

    // `words` carries per-phone placeholders (only the phone count per variant matters — the
    // options closure keys on position, not the phone value), exactly like Python passes
    // `list(range(...))`-style targets whose values are ignored by a custom options localizer.
    let words: [[[Int]]] = phoneWords.map { $0.map { Array(0..<$0.count) } }
    let options: (Int, Int, Int) -> [[Int]] = { wi, vi, pi in
      XeusInventory.accepted(phoneWords[wi][vi][pi], vocab)
    }

    let result = XeusLattice.alignVariants(matrix, words, options: options)
    #expect(result != nil)
    let (selected, spans) = result!

    // Exhaustive cross-check: the lattice-selected variant combination must be the best-scoring
    // combination out of all 4, by exhaustive `path` Viterbi scoring — the property Python's
    // 30-trial Dirichlet test asserts, replicated here on the persisted first draw.
    func score(_ indices: [Int]) -> Double {
      var ids: [Int] = []
      for (word, i) in zip(phoneWords, indices) { for phone in word[i] { ids.append(vocab[phone]!) } }
      return XeusCTC.path(matrix, ids, trace: true).score
    }
    var best: [Int] = [0, 0]
    var bestScore = score(best)
    for a in 0..<2 {
      for b in 0..<2 {
        let s = score([a, b])
        if s > bestScore { bestScore = s; best = [a, b] }
      }
    }
    #expect(abs(score(selected) - bestScore) < 1e-12)

    #expect(selected == asIntArray(golden["selected"]!))
    #expect(spans == asIntCube(golden["spans"]!))
    #expect(best == asIntArray(golden["bestComboByExhaustiveSearch"]!))
  }

  // MARK: test_repeated_phones_across_words_need_blank

  @Test func repeatedPhonesAcrossWordsNeedBlank() throws {
    let golden = try goldenCase("repeated_phones_across_words_need_blank")
    let vocab = asVocab(golden["vocab"]!)
    let phoneWords = asStringCube(golden["words"]!) // [[["v"]],[["v"]]]
    let words: [[[Int]]] = phoneWords.map { $0.map { Array(0..<$0.count) } }
    let options: (Int, Int, Int) -> [[Int]] = { wi, vi, pi in
      XeusInventory.accepted(phoneWords[wi][vi][pi], vocab)
    }

    // No blank frame between the two identical words: the word boundary does not substitute for
    // the mandatory CTC blank, so no alignment exists.
    let without = golden["withoutBlank"] as! [String: Any]
    let withoutLp = asLp(without["lp"]!)
    #expect(without["result"] is NSNull)
    #expect(XeusLattice.alignVariants(withoutLp, words, options: options) == nil)

    // With an intervening blank frame the lattice aligns, one phone per word.
    let withBlank = golden["withBlank"] as! [String: Any]
    let withLp = asLp(withBlank["lp"]!)
    let result = XeusLattice.alignVariants(withLp, words, options: options)
    #expect(result != nil)
    let (selected, spans) = result!
    #expect(selected == asIntArray(withBlank["selected"]!))
    #expect(spans == asIntCube(withBlank["spans"]!))
  }

  // MARK: split_affricate_span_covers_both_emissions (golden-only lattice case)

  @Test func splitAffricateSpanCoversBothEmissions() throws {
    let golden = try goldenCase("split_affricate_span_covers_both_emissions")
    let vocab = asVocab(golden["vocab"]!)
    let phoneWords = asStringCube(golden["words"]!) // [[["tʃ","ə"]]]
    let matrix = asLp(golden["lp"]!)
    let words: [[[Int]]] = phoneWords.map { $0.map { Array(0..<$0.count) } }
    let options: (Int, Int, Int) -> [[Int]] = { wi, vi, pi in
      XeusInventory.accepted(phoneWords[wi][vi][pi], vocab)
    }

    let result = XeusLattice.alignVariants(matrix, words, options: options)
    #expect(result != nil)
    let (selected, spans) = result!
    #expect(selected == asIntArray(golden["selected"]!))
    #expect(spans == asIntCube(golden["spans"]!))
  }

  // MARK: test_align_variants_accepts_per_position_options

  @Test func alignVariantsAcceptsPerPositionOptions() throws {
    // Not in the golden fixture: constructed directly, mirroring the Python unit test.
    let matrix = lp([[4: 1.0], [0: 1.0], [5: 1.0]])
    let words: [[[Int]]] = [[[0, 1]]] // 1 word, 1 variant, 2 placeholder phones
    let options: (Int, Int, Int) -> [[Int]] = { _, _, pi in pi == 0 ? [[4]] : [[5]] }
    let result = XeusLattice.alignVariants(matrix, words, options: options)
    #expect(result != nil)
    let (selected, spans) = result!
    #expect(selected == [0])
    #expect(spans == [[[0, 1], [2, 3]]])
  }

  // MARK: test_align_units_locates_pair_unit_on_single_rhotic_token

  @Test func alignUnitsLocatesPairUnitOnSingleRhoticToken() throws {
    let golden = try goldenCase("pair_unit_localizes_on_single_rhotic_token_via_licensed_class_d")
    let vocab = asVocab(golden["vocab"]!)
    let phoneList = (golden["phones"] as! [Any]).map { $0 as! String }
    let matrix = asLp(golden["lp"]!)

    let units = try XeusInventory.buildUnits([("w", phoneList)], vocab)

    // Cross-check the built units against the golden unit table (allowed/cond/indices/id).
    let goldenUnits = golden["units"] as! [[String: Any]]
    #expect(units.count == goldenUnits.count)
    for (unit, gu) in zip(units, goldenUnits) {
      #expect(unit.allowed == asIntMatrix(gu["allowed"]!))
      #expect(unit.cond == asIntMatrix(gu["cond"]!))
      #expect(unit.indices == asIntArray(gu["indices"]!))
      #expect(unit.id == gu["id"] as! String)
    }

    // Without licensing the class-D [ɜ˞] realization, the schwa+/ɹ/ pair unit cannot land on the
    // single r-colored-schwa frame; its span stretches over the trailing blank instead.
    let withoutExpected = (golden["withoutLicensedExtra"] as! [String: Any])["spans"]!
    let withoutSpans = XeusLattice.alignUnits(matrix, units, extra: nil)
    #expect(withoutSpans != nil)
    #expect(withoutSpans! == asIntMatrix(withoutExpected))

    // Licensing [ɜ˞] as `extra` for the pair unit localizes it at [4,5].
    let withDict = golden["withLicensedExtraForPairUnit"] as! [String: Any]
    let extra = asIntCube(withDict["extra"]!)
    let withSpans = XeusLattice.alignUnits(matrix, units, extra: extra)
    #expect(withSpans != nil)
    #expect(withSpans! == asIntMatrix(withDict["spans"]!))
  }
}
