import Foundation
import Testing
@testable import ToSpeech

/// Parity tests ported from `scripts/assessment/phoneticxeus/test_evidence.py`'s CTC cases —
/// `test_forward_matches_exhaustive_paths_and_repeats`, `test_impossible_repeat_rejected`,
/// `test_realization_probability_sums_disjoint_ctc_sequences_once` — using the SAME `lp` matrices
/// (built the same way as Python's `self.lp` / `dump_golden.py`'s `lp_from_rows` helper), plus a
/// cross-check of every case against the Task 2 golden fixture
/// `ToSpeechTests/Fixtures/XeusNative/ctc-golden.json`, which was generated by
/// `scripts/assessment/phoneticxeus/dump_golden.py` running the real Python `evidence.py`.
@Suite struct XeusCTCTests {
  // MARK: - lp construction (byte-for-byte port of Python's `self.lp` / `lp_from_rows`)

  /// Builds a `[frames x vocabSize]` log-prob matrix: floor `1e-8` everywhere, overwritten with
  /// the given token probabilities, renormalized per frame to sum to 1, then logged — identical
  /// recipe to `test_evidence.py`'s `self.lp` and `dump_golden.py`'s `lp_from_rows`.
  private func lp(_ rows: [[Int: Double]], vocabSize: Int = 428, floor: Double = 1e-8) -> [[Double]] {
    rows.map { values in
      var row = [Double](repeating: floor, count: vocabSize)
      for (token, prob) in values { row[token] = prob }
      let sum = row.reduce(0, +)
      return row.map { Foundation.log($0 / sum) }
    }
  }

  /// Collapses a frame-label sequence the way `itertools.groupby(seq)` + `x != 0` does in the
  /// Python tests: keep the first label of each run of identical values, drop blanks (id 0).
  private func collapse(_ sequence: [Int]) -> [Int] {
    var result: [Int] = []
    for (i, x) in sequence.enumerated() where x != 0 && (i == 0 || sequence[i - 1] != x) {
      result.append(x)
    }
    return result
  }

  // MARK: - Golden fixture loading (ToSpeechTests/Fixtures/XeusNative/ctc-golden.json)

  private func loadGoldenCases() throws -> [[String: Any]] {
    let url = URL(fileURLWithPath: #filePath)
      .deletingLastPathComponent()
      .appendingPathComponent("Fixtures/XeusNative/ctc-golden.json")
    let data = try Data(contentsOf: url)
    let json = try JSONSerialization.jsonObject(with: data) as! [String: Any]
    return json["cases"] as! [[String: Any]]
  }

  private func goldenCase(_ name: String) throws -> [String: Any] {
    let cases = try loadGoldenCases()
    guard let match = cases.first(where: { $0["name"] as? String == name }) else {
      Issue.record("golden case not found: \(name)")
      fatalError("golden case not found: \(name)")
    }
    return match
  }

  /// `dump_golden.py`'s `jsonable()` writes `-inf`/`inf`/`nan` as the quoted sentinel strings
  /// `"-Infinity"`/`"Infinity"`/`"NaN"` (valid JSON, explicit on both ends); everything else is a
  /// plain JSON number.
  private func asDouble(_ any: Any) -> Double {
    if let s = any as? String {
      switch s {
      case "-Infinity": return -Double.infinity
      case "Infinity": return Double.infinity
      case "NaN": return Double.nan
      default: preconditionFailure("unexpected numeric sentinel: \(s)")
      }
    }
    return (any as! NSNumber).doubleValue
  }

  private func asIntArray(_ any: Any) -> [Int] {
    (any as! [Any]).map { ($0 as! NSNumber).intValue }
  }

  private func asIntMatrix(_ any: Any) -> [[Int]] {
    (any as! [Any]).map { asIntArray($0) }
  }

  // MARK: test_forward_matches_exhaustive_paths_and_repeats

  @Test func forwardMatchesExhaustivePathsAndRepeats() throws {
    let rows: [[Int: Double]] = [[0: 0.4, 4: 0.4, 5: 0.2], [0: 0.3, 4: 0.3, 5: 0.4], [0: 0.2, 4: 0.5, 5: 0.3]]
    let matrix = lp(rows)
    let targets: [[Int]] = [[], [4], [4, 4], [4, 5], [5, 4]]

    // Sanity: our hand-built matrix matches the golden fixture's persisted `lp` byte-for-byte
    // (within float round-trip tolerance), so a transcription typo in `rows` above can't silently
    // pass by coincidence.
    let golden = try goldenCase("forward_matches_exhaustive_paths_and_repeats")
    let goldenLp = (golden["lp"] as! [Any]).map { row in (row as! [Any]).map { asDouble($0) } }
    #expect(goldenLp.count == matrix.count)
    for (a, b) in zip(matrix, goldenLp) {
      #expect(a.count == b.count)
      for (x, y) in zip(a, b) { #expect(abs(x - y) < 1e-9) }
    }

    let goldenCases = golden["cases"] as! [[String: Any]]
    #expect(goldenCases.count == targets.count)

    for (target, goldenTarget) in zip(targets, goldenCases) {
      #expect(asIntArray(goldenTarget["target"]!) == target)

      // Brute-force cross-check: enumerate every length-3 frame path over {blank, 4, 5}, collapse
      // consecutive repeats and drop blanks, sum the probability of paths whose collapsed output
      // equals `target` — exactly what test_forward_matches_exhaustive_paths_and_repeats does.
      var bruteForceTotal = 0.0
      for a in [0, 4, 5] {
        for b in [0, 4, 5] {
          for c in [0, 4, 5] {
            let seq = [a, b, c]
            if collapse(seq) == target {
              bruteForceTotal += exp(matrix[0][a] + matrix[1][b] + matrix[2][c])
            }
          }
        }
      }

      let score = XeusCTC.path(matrix, target, trace: false).score
      #expect(abs(exp(score) - bruteForceTotal) < 1e-9, "target \(target): brute-force mismatch")

      let goldenScore = asDouble(goldenTarget["score"]!)
      #expect(abs(score - goldenScore) < 1e-9, "target \(target): golden mismatch")
    }
  }

  // MARK: test_impossible_repeat_rejected

  @Test func impossibleRepeatRejected() throws {
    let matrix = lp([[4: 1.0], [4: 1.0]])
    let result = XeusCTC.path(matrix, [4, 4], trace: true)
    #expect(result.score == -Double.infinity)
    #expect(result.spans == nil)

    let golden = try goldenCase("impossible_repeat_rejected")
    #expect(golden["spans"] is NSNull)
    let goldenScore = asDouble(golden["score"]!)
    #expect(goldenScore == -Double.infinity)
    #expect(result.score == goldenScore)
  }

  // MARK: test_realization_probability_sums_disjoint_ctc_sequences_once

  @Test func realizationProbabilitySumsDisjointCtcSequencesOnce() throws {
    let matrix = lp([[0: 0.4, 4: 0.3, 5: 0.3], [0: 0.2, 4: 0.4, 5: 0.4]])

    // Brute-force cross-check over every length-2 frame path, exactly like the Python test.
    var bruteForceTotal = 0.0
    for a in [0, 4, 5] {
      for b in [0, 4, 5] {
        let seq = [a, b]
        let collapsed = collapse(seq)
        if collapsed == [4] || collapsed == [5] {
          bruteForceTotal += exp(matrix[0][a] + matrix[1][b])
        }
      }
    }

    // [4] appears twice in the input sequences; realizationLikelihood must count it once.
    let score = XeusCTC.realizationLikelihood(matrix, [[4], [5], [4]])
    #expect(abs(exp(score) - bruteForceTotal) < 1e-9)

    let golden = try goldenCase("realization_likelihood_sums_disjoint_sequences_once")
    #expect(asIntMatrix(golden["sequences"]!) == [[4], [5], [4]])
    let goldenScore = asDouble(golden["score"]!)
    #expect(abs(score - goldenScore) < 1e-9)
  }

  // MARK: trace_recovers_emission_span_for_a_present_target (golden case 4; trace half of
  // test_wrong_target_not_green_just_because_alignment_succeeds)

  @Test func traceRecoversEmissionSpanForAPresentTarget() throws {
    let matrix = lp([[0: 0.95, 5: 0.05], [5: 0.98, 4: 0.001], [5: 0.95, 4: 0.001], [0: 0.99]])
    let result = XeusCTC.path(matrix, [4], trace: true)
    #expect(result.spans != nil)

    let golden = try goldenCase("trace_recovers_emission_span_for_a_present_target")
    let goldenScore = asDouble(golden["score"]!)
    let goldenSpans = asIntMatrix(golden["spans"]!)
    #expect(abs(result.score - goldenScore) < 1e-9)
    #expect(result.spans! == goldenSpans)
  }
}
