import Foundation
import Testing
@testable import ToSpeech

/// Parity tests ported from `scripts/assessment/phoneticxeus/test_evidence.py`'s assessment cases
/// — `test_wrong_target_not_green_just_because_alignment_succeeds`,
/// `test_blank_only_and_ambiguous_are_not_correct`, `test_length_only_difference_is_accepted_quality`,
/// `test_split_probability_between_accepted_k_realizations_is_not_a_phone_error`,
/// `test_support_floor_thirty_admits_one_frame_spike_with_strong_margin`,
/// `test_assess_phones_still_rejects_wrong_and_ambiguous`,
/// `test_confusion_gate_flags_only_confusable_substitutions`, `test_coverage_counts_scored_fraction`,
/// `test_coverage_zero_when_no_rows`, `test_weak_form_and_length_never_incorrect` — using the SAME
/// hand-built `lp` matrices as the Python source, plus a comprehensive cross-check of every case in
/// the Task 2 golden fixture `ToSpeechTests/Fixtures/XeusNative/assess-golden.json` (17 phone cases
/// + 2 coverage cases), which was generated by `scripts/assessment/phoneticxeus/dump_golden.py`
/// running the real Python `evidence.py`.
@Suite struct XeusAssessTests {
  // MARK: - lp construction (byte-for-byte port of Python's `self.lp` / `lp_from_rows`)

  private func lp(_ rows: [[Int: Double]], vocabSize: Int = 428, floor: Double = 1e-8) -> [[Double]] {
    rows.map { values in
      var row = [Double](repeating: floor, count: vocabSize)
      for (token, prob) in values { row[token] = prob }
      let sum = row.reduce(0, +)
      return row.map { Foundation.log($0 / sum) }
    }
  }

  /// Port of `test_evidence.py`'s `self.vocab428(**names)`: every id 0..<428 named `x<id>`, then
  /// `<blank>` and any real IPA overrides.
  private func vocab428(_ overrides: [String: Int] = [:]) -> [String: Int] {
    var vocab: [String: Int] = [:]
    for i in 0..<428 { vocab["x\(i)"] = i }
    vocab["<blank>"] = 0
    for (symbol, id) in overrides { vocab[symbol] = id }
    return vocab
  }

  // MARK: - Golden fixture loading (ToSpeechTests/Fixtures/XeusNative/assess-golden.json)

  private func loadGolden() throws -> [String: Any] {
    let url = URL(fileURLWithPath: #filePath)
      .deletingLastPathComponent()
      .appendingPathComponent("Fixtures/XeusNative/assess-golden.json")
    let data = try Data(contentsOf: url)
    return try JSONSerialization.jsonObject(with: data) as! [String: Any]
  }

  private func asDouble(_ any: Any) -> Double { (any as! NSNumber).doubleValue }
  private func asInt(_ any: Any) -> Int { (any as! NSNumber).intValue }
  private func asStringArray(_ any: Any) -> [String] { (any as! [Any]).map { $0 as! String } }

  private func asLp(_ any: Any) -> [[Double]] {
    (any as! [Any]).map { row in (row as! [Any]).map { asDouble($0) } }
  }

  private func asVocab(_ any: Any) -> [String: Int] {
    (any as! [String: Any]).mapValues { ($0 as! NSNumber).intValue }
  }

  private func asThresholds(_ any: Any) -> XeusAssess.Thresholds {
    let dict = any as! [String: Any]
    return XeusAssess.Thresholds(
      support: asDouble(dict["support"]!), margin: asDouble(dict["margin"]!),
      entropy: asDouble(dict["entropy"]!), competitor: asDouble(dict["competitor"]!),
      strength: asDouble(dict["strength"]!))
  }

  /// Cross-checks one expanded phone row against its golden dict.
  ///
  /// `closestPhone` is skipped for the two "support floor" cases: their fixture deliberately
  /// spreads probability evenly across 20 non-canonical competitor ids, so which exact tied id
  /// numpy's (unstable) `argsort` — and therefore this port's stable-sort equivalent — reports as
  /// the winner is not reproducible across implementations; the Python test itself does not
  /// assert `closestPhone` there either (see `supportFloorThirtyAdmitsOneFrameSpikeWithStrongMargin`
  /// below).
  ///
  /// `skipNumericFields` lets a case opt individual numeric fields out of the golden comparison.
  /// Previously used for `missing_glide_cannot_borrow_from_first_vowel`, whose fixture vocab has
  /// a precomposed `'ẽ'` (U+1EBD) key: Python's plain (non-Unicode-normalizing) string equality
  /// treats that as different from the decomposed `'e'+'̃'` `_nasal()` looks up, so
  /// `evidence.accepted('eɪ', vocab)` finds only 2 realizations, not the mathematically-equivalent
  /// 4. `XeusInventory` now does the same code-point-exact vocab lookup (see `XeusInventory
  /// .ExactKey`/`exactVocab`), so this case matches Python exactly and no longer needs a skip —
  /// kept as a general-purpose escape hatch for any future case that legitimately needs one.
  private func expectRowMatches(
    _ row: XeusAssess.PhoneRow, _ golden: [String: Any], checkClosestPhone: Bool,
    skipNumericFields: Set<String> = [], tolerance: Double = 1e-6, caseName: String = ""
  ) {
    #expect(row.status == golden["status"] as! String)
    #expect(row.reason == golden["reason"] as? String)
    #expect(row.expected == golden["expected"] as! String)
    #expect(row.windowStart == asInt(golden["windowStart"]!))
    #expect(row.windowEnd == asInt(golden["windowEnd"]!))
    #expect(row.chosen == asStringArray(golden["chosen"]!))
    if checkClosestPhone { #expect(row.closestPhone == golden["closestPhone"] as? String) }

    for (field, value, goldenKey) in [
      ("start", row.start, "start"), ("end", row.end, "end"),
      ("emissionStart", row.emissionStart, "emissionStart"), ("emissionEnd", row.emissionEnd, "emissionEnd"),
      ("expectedProbability", row.expectedProbability, "expectedProbability"),
      ("expectedTokenProbability", row.expectedTokenProbability, "expectedTokenProbability"),
      ("expectedLogLikelihood", row.expectedLogLikelihood, "expectedLogLikelihood"),
      ("alternativeLogLikelihood", row.alternativeLogLikelihood, "alternativeLogLikelihood"),
      ("deletionLogLikelihood", row.deletionLogLikelihood, "deletionLogLikelihood"),
      ("logMargin", row.logMargin, "logMargin"), ("confidence", row.confidence, "confidence"),
    ] as [(String, Double?, String)] {
      guard !skipNumericFields.contains(field) else { continue }
      guard let value else { Issue.record("missing \(field)"); continue }
      let goldenValue = asDouble(golden[goldenKey]!)
      #expect(abs(value - goldenValue) < tolerance, "\(caseName) \(field): \(value) vs golden \(goldenValue)")
    }
  }

  // MARK: comprehensive golden cross-check (all 17 phone cases + 2 coverage cases)

  @Test func allGoldenPhoneCasesMatch() throws {
    let golden = try loadGolden()
    let phoneCases = golden["phoneCases"] as! [[String: Any]]
    // These four cases have no genuine (non-floor) competitor at all — every candidate the
    // grader can see sits at the same synthetic floor probability, so which exactly-tied id
    // numpy's (unstable) `argsort` — and therefore this port's stable-sort equivalent — reports
    // as `closestPhone` is not reproducible across implementations, though it cannot change the
    // decision (the competitor branch never fires on floor-level evidence either way). None of
    // these are asserted on `closestPhone` by the Python test either.
    let skipClosestPhone: Set<String> = [
      "support_floor_default_admits_thin_but_present_evidence",
      "support_floor_stricter_threshold_rejects_the_same_evidence",
      "length_only_difference_is_accepted_quality",
      "dark_l_is_not_a_different_uk_phoneme",
    ]
    for c in phoneCases {
      let name = c["name"] as! String
      let vocab = asVocab(c["vocab"]!)
      let phones = asStringArray(c["phones"]!)
      let duration = asDouble(c["duration"]!)
      let matrix = asLp(c["lp"]!)
      let thresholds: XeusAssess.Thresholds
      if let rawThresholds = c["thresholds"] as? [String: Any] {
        thresholds = asThresholds(rawThresholds)
      } else {
        thresholds = XeusAssess.Thresholds()
      }
      let rows = try XeusAssess.assessPhones(matrix, phones, vocab, duration: duration, thresholds: thresholds)
      let goldenRows = c["result"] as! [[String: Any]]
      #expect(rows.count == goldenRows.count, "case \(name)")
      for (row, goldenRow) in zip(rows, goldenRows) {
        expectRowMatches(
          row, goldenRow, checkClosestPhone: !skipClosestPhone.contains(name), caseName: name)
      }
    }
  }

  @Test func allGoldenCoverageCasesMatch() throws {
    let golden = try loadGolden()
    let coverageCases = golden["coverageCases"] as! [[String: Any]]
    for c in coverageCases {
      let statuses = (c["rows"] as! [Any]).map { (($0 as! [String: Any])["status"] as! String) }
      let rows = statuses.map { XeusAssess.AssessRow(status: $0) }
      let result = c["result"] as! [String: Any]
      let coverage = XeusAssess.coverage(rows)
      #expect(coverage.total == asInt(result["total"]!))
      #expect(coverage.scored == asInt(result["scored"]!))
      #expect(coverage.correct == asInt(result["correct"]!))
      #expect(coverage.incorrect == asInt(result["incorrect"]!))
      #expect(coverage.unassessed == asInt(result["unassessed"]!))
      #expect(abs(coverage.coverage - asDouble(result["coverage"]!)) < 1e-9)
    }
  }

  // MARK: test_wrong_target_not_green_just_because_alignment_succeeds

  @Test func wrongTargetNotGreenJustBecauseAlignmentSucceeds() throws {
    let vocab = vocab428(["θ": 4, "s": 5])
    let matrix = lp([[0: 0.95, 5: 0.05], [5: 0.98, 4: 0.001], [5: 0.95, 4: 0.001], [0: 0.99]])
    let (_, spans) = XeusCTC.path(matrix, [4], trace: true)
    #expect(spans != nil)
    let rows = try XeusAssess.assessPhones(matrix, ["θ"], vocab, duration: 0.08)
    #expect(rows[0].status != "correct")
    #expect(rows[0].closestPhone == "s")
  }

  // MARK: test_blank_only_and_ambiguous_are_not_correct

  @Test func blankOnlyAndAmbiguousAreNotCorrect() throws {
    let vocab = vocab428(["θ": 4, "s": 5])
    let rowSets: [[[Int: Double]]] = [
      Array(repeating: [0: 0.9999], count: 5),
      Array(repeating: [4: 0.39, 5: 0.41, 0: 0.2], count: 5),
    ]
    for rows in rowSets {
      let matrix = lp(rows)
      let result = try XeusAssess.assessPhones(matrix, ["θ"], vocab, duration: 0.1)
      #expect(result[0].status == "uncertain")
    }
  }

  // MARK: test_length_only_difference_is_accepted_quality

  @Test func lengthOnlyDifferenceIsAcceptedQuality() throws {
    let vocab = vocab428(["iː": 4, "i": 5])
    let matrix = lp([[0: 0.95], [5: 0.98, 4: 0.001], [5: 0.95, 4: 0.001], [0: 0.99]])
    let row = try XeusAssess.assessPhones(matrix, ["iː"], vocab, duration: 0.08)[0]
    #expect(row.status == "correct")
    #expect(row.expected == "iː")
  }

  // MARK: test_split_probability_between_accepted_k_realizations_is_not_a_phone_error

  @Test func splitProbabilityBetweenAcceptedKRealizationsIsNotAPhoneError() throws {
    let vocab = vocab428(["k": 4, "kʰ": 5, "ɡ": 6])
    let matrix = lp([[0: 0.999], [4: 0.4426, 5: 0.5466, 6: 0.001], [0: 0.999]])
    let row = try XeusAssess.assessPhones(matrix, ["k"], vocab, duration: 0.06)[0]
    #expect(row.status == "correct")
    #expect(row.expectedProbability! > 0.98)
    #expect(row.expectedTokenProbability! < 0.60)

    let wrong = lp([[0: 0.999], [4: 0.04, 5: 0.04, 6: 0.92], [0: 0.999]])
    let wrongRow = try XeusAssess.assessPhones(wrong, ["k"], vocab, duration: 0.06)[0]
    #expect(wrongRow.status != "correct")
  }

  // MARK: test_support_floor_thirty_admits_one_frame_spike_with_strong_margin

  @Test func supportFloorThirtyAdmitsOneFrameSpikeWithStrongMargin() throws {
    let v = vocab428(["ð": 4, "h": 5])
    var frame1: [Int: Double] = [4: 0.45]
    for i in 0..<20 { frame1[10 + i] = 0.0275 }
    let matrix = lp([[0: 0.99], frame1, [0: 0.99]])
    let row = try XeusAssess.assessPhones(matrix, ["ð"], v, duration: 0.06)[0]
    #expect(row.status == "correct")
    #expect(row.expectedProbability! < 0.60)

    let units = [XeusInventory.Unit(word: "w", indices: [0], display: ["ð"], allowed: XeusInventory.accepted("ð", v), cond: [], wordInitial: false)]
    let strict = XeusAssess.assessUnits(matrix, units, [units[0].allowed], v, duration: 0.06, thresholds: XeusAssess.Thresholds(support: 0.60))
    #expect(strict[0].status == "uncertain")
  }

  // MARK: test_assess_phones_still_rejects_wrong_and_ambiguous

  @Test func assessPhonesStillRejectsWrongAndAmbiguous() throws {
    let v = vocab428(["θ": 4, "s": 5])
    let confident = lp([[0: 0.95, 5: 0.05], [5: 0.98, 4: 0.001], [5: 0.95, 4: 0.001], [0: 0.99]])
    #expect(try XeusAssess.assessPhones(confident, ["θ"], v, duration: 0.08)[0].status == "likelyIncorrect")

    let ambiguous = lp(Array(repeating: [4: 0.39, 5: 0.41, 0: 0.2], count: 5))
    #expect(try XeusAssess.assessPhones(ambiguous, ["θ"], v, duration: 0.1)[0].status == "uncertain")
  }

  // MARK: test_confusion_gate_flags_only_confusable_substitutions

  @Test func confusionGateFlagsOnlyConfusableSubstitutions() throws {
    #expect(XeusInventory.CONFUSION["v"]!.contains("w"))
    let v = vocab428(["v": 4, "w": 5])
    let matrix = lp([[0: 0.99], [5: 0.98, 4: 0.001], [5: 0.98, 4: 0.001], [0: 0.99]])
    #expect(try XeusAssess.assessPhones(matrix, ["v"], v, duration: 0.08)[0].status == "likelyIncorrect")

    let v2 = vocab428(["v": 4])
    let matrix2 = lp([[0: 0.99], [99: 0.98, 4: 0.001], [99: 0.98, 4: 0.001], [0: 0.99]])
    let row = try XeusAssess.assessPhones(matrix2, ["v"], v2, duration: 0.08)[0]
    #expect(row.status == "uncertain")
    #expect(row.reason == "ambiguousSubstitution")
  }

  // MARK: test_coverage_counts_scored_fraction

  @Test func coverageCountsScoredFraction() {
    #expect(XeusAssess.policy == "xeus-uk-decision-v6-word-gated")
    let rows = ["correct", "likelyIncorrect", "uncertain", "correct"].map { XeusAssess.AssessRow(status: $0) }
    let c = XeusAssess.coverage(rows)
    #expect(c.total == 4)
    #expect(c.scored == 3)
    #expect(c.correct == 2)
    #expect(c.incorrect == 1)
    #expect(c.unassessed == 1)
    #expect(abs(c.coverage - 0.75) < 1e-9)
  }

  // MARK: test_coverage_zero_when_no_rows

  @Test func coverageZeroWhenNoRows() {
    let c = XeusAssess.coverage([])
    #expect(c == XeusAssess.Coverage(total: 0, scored: 0, correct: 0, incorrect: 0, unassessed: 0, coverage: 0.0))
  }

  // MARK: test_weak_form_and_length_never_incorrect

  @Test func weakFormAndLengthNeverIncorrect() throws {
    #expect(XeusInventory.mapping == "xeus-uk-inventory-v4")
    let v = vocab428(["ʊ": 4, "ə": 5])
    let matrix = lp([[0: 0.99], [5: 0.98, 4: 0.001], [5: 0.95, 4: 0.001], [0: 0.99]])
    #expect(try XeusAssess.assessPhones(matrix, ["ʊ"], v, duration: 0.08)[0].status != "likelyIncorrect")
    #expect(XeusInventory.conditional("ʊ", v).contains([v["ə"]!]))
  }
}
