import Foundation

/// Teaching content for the conventional 44-sound RP chart. This catalog is
/// independent of model coverage and never supplies assessment grades.
struct UKSoundGuide: Identifiable, Sendable {
  enum Group: String, CaseIterable, Sendable { case vowels, diphthongs, consonants }
  let symbol: String
  let group: Group
  let examples: [String]
  let contrast: [String]
  let mouthVI: String
  let mouthEN: String
  let cueVI: String
  let cueEN: String
  var id: String { symbol }
  func mouth(locale: Locale) -> String { locale.language.languageCode?.identifier == "vi" ? mouthVI : mouthEN }
  func cue(locale: Locale) -> String { locale.language.languageCode?.identifier == "vi" ? cueVI : cueEN }
}

enum UKSoundLibrary {
  static let version = "uk-articulation-v1"
  // Lookup aliases are for teaching only. Never feed them to an acoustic scorer.
  static let aliases = ["ɛ": "e", "g": "ɡ", "r": "ɹ", "ɛə": "eə", "ɛː": "eə",
    "ɪː": "ɪə", "ʊː": "ʊə", "i": "iː", "u": "uː", "ɐ": "ʌ", "ʔ": "t",
    "l̩": "l", "n̩": "n", "m̩": "m"]
  static func guide(for symbol: String) -> UKSoundGuide? {
    all.first { $0.symbol == (aliases[symbol] ?? symbol) }
  }
  static func audioResource(for symbol: String) -> String? {
    guard let canonical = guide(for: symbol)?.symbol,
      let index = all.firstIndex(where: { $0.symbol == canonical }) else { return nil }
    return String(format: "UKPhoneme_%02d", index + 1)
  }
  static let all: [UKSoundGuide] = [
    .init(symbol: "iː", group: .vowels, examples: ["see", "green"], contrast: ["ship", "sheep"], mouthVI: "Lưỡi cao và hướng ra trước; môi thả lỏng, hơi bè. Giữ chất âm ổn định.", mouthEN: "Tongue high and forward; lips relaxed and slightly spread. Keep the vowel steady.", cueVI: "So sánh ship – sheep: khác cả chất âm, không chỉ kéo dài /ɪ/.", cueEN: "Compare ship – sheep: change vowel quality, not just the length of /ɪ/."),
    .init(symbol: "ɪ", group: .vowels, examples: ["sit", "fish"], contrast: ["ship", "sheep"], mouthVI: "Lưỡi ở phía trước nhưng thấp và thả lỏng hơn /iː/; hàm mở nhẹ.", mouthEN: "Keep the tongue near the front, lower and more relaxed than for /iː/; open the jaw slightly.", cueVI: "Đọc gọn; đừng biến sit thành seat.", cueEN: "Keep it short and relaxed; avoid changing sit into seat."),
    .init(symbol: "e", group: .vowels, examples: ["bed", "ten"], contrast: ["bed", "bad"], mouthVI: "Lưỡi ở trước, hàm mở vừa; môi không tròn. Ký hiệu /ɛ/ cũng thường dùng cho âm này.", mouthEN: "Tongue forward, jaw partly open, lips unrounded. This vowel is also commonly written /ɛ/.", cueVI: "Mở hàm ít hơn /æ/; phân biệt bed – bad.", cueEN: "Open the jaw less than for /æ/; distinguish bed from bad."),
    .init(symbol: "æ", group: .vowels, examples: ["cat", "black"], contrast: ["bed", "bad"], mouthVI: "Hạ hàm, lưỡi thấp ở phía trước; môi không tròn.", mouthEN: "Lower the jaw; keep the tongue low and forward, with unrounded lips.", cueVI: "Đừng thu hẹp thành /e/; thử chuyển bed → bad bằng cách mở hàm.", cueEN: "Avoid narrowing it to /e/; move from bed to bad by opening the jaw."),
    .init(symbol: "ɑː", group: .vowels, examples: ["car", "father"], contrast: ["cart", "cat"], mouthVI: "Hàm mở rộng, lưỡi thấp và lùi; môi thả lỏng, không tròn.", mouthEN: "Open the jaw widely; tongue low and back, lips relaxed and unrounded.", cueVI: "Với RP, car đứng riêng không có /r/ ở cuối. Không thêm âm /r/ chỉ vì có chữ r.", cueEN: "In non-rhotic RP, car in isolation has no final /r/. Do not add one just because it is written."),
    .init(symbol: "ɒ", group: .vowels, examples: ["hot", "clock"], contrast: ["cot", "cart"], mouthVI: "Lưỡi thấp ở phía sau; môi hơi tròn, hàm mở.", mouthEN: "Tongue low and back; round the lips lightly with an open jaw.", cueVI: "Giữ âm ngắn; tránh đổi thành /ɑː/ kiểu cart.", cueEN: "Keep it short; avoid replacing it with the /ɑː/ in cart."),
    .init(symbol: "ɔː", group: .vowels, examples: ["law", "talk"], contrast: ["cot", "caught"], mouthVI: "Lưỡi ở phía sau và cao hơn /ɒ/; môi tròn, hàm mở vừa.", mouthEN: "Tongue back and higher than for /ɒ/; round the lips and partly open the jaw.", cueVI: "Giữ nguyên âm đơn, không lướt thành /əʊ/.", cueEN: "Keep a steady vowel rather than gliding towards /əʊ/."),
    .init(symbol: "ʊ", group: .vowels, examples: ["book", "foot"], contrast: ["full", "fool"], mouthVI: "Lưỡi tương đối cao, hơi lùi; môi tròn nhẹ, thả lỏng.", mouthEN: "Tongue fairly high and slightly back; lips loosely rounded.", cueVI: "Đừng chỉ rút ngắn /uː/; full và fool khác cả chất âm.", cueEN: "Do not simply shorten /uː/; full and fool differ in vowel quality too."),
    .init(symbol: "uː", group: .vowels, examples: ["blue", "food"], contrast: ["full", "fool"], mouthVI: "Lưỡi cao; môi tròn vừa. Trong giọng UK hiện đại, lưỡi có thể ở giữa hơn cách mô tả truyền thống.", mouthEN: "Keep the tongue high and lips moderately rounded. Modern UK speakers may use a more central tongue position.", cueVI: "Không ép môi nhọn quá mức; so sánh food – foot.", cueEN: "Avoid excessive lip tension; compare food and foot."),
    .init(symbol: "ʌ", group: .vowels, examples: ["cup", "love"], contrast: ["cap", "cup"], mouthVI: "Hàm mở vừa đến rộng, môi không tròn; lưỡi thả lỏng ở vùng giữa.", mouthEN: "Jaw moderately open, lips unrounded; keep the tongue relaxed near the centre.", cueVI: "Đừng đọc như /æ/ phía trước. Chất âm STRUT thay đổi giữa các giọng UK.", cueEN: "Avoid the forward /æ/ quality. The STRUT vowel varies across UK accents."),
    .init(symbol: "ɜː", group: .vowels, examples: ["bird", "work"], contrast: ["bed", "bird"], mouthVI: "Lưỡi ở giữa, hàm mở vừa, môi thả lỏng; giữ âm ổn định.", mouthEN: "Tongue central, jaw partly open, lips relaxed; hold a steady vowel.", cueVI: "RP không uốn âm theo /r/ trong bird; đừng đổi thành nguyên âm có màu r của giọng Mỹ.", cueEN: "RP bird has no r-coloured vowel; avoid adding American-style rhoticity."),
    .init(symbol: "ə", group: .vowels, examples: ["about", "sofa"], contrast: ["about", "sofa"], mouthVI: "Thả lỏng môi, hàm và lưỡi ở giữa miệng; phát âm nhẹ ở âm tiết không nhấn.", mouthEN: "Relax the lips, jaw and tongue near the centre; use a light unstressed syllable.", cueVI: "about: nghe âm đầu; sofa: nghe âm cuối. Đừng nhấn mạnh mọi âm tiết.", cueEN: "Listen to the start of about and the end of sofa. Avoid stressing every syllable."),
    .init(symbol: "eɪ", group: .diphthongs, examples: ["day", "rain"], contrast: ["pen", "pain"], mouthVI: "Bắt đầu ở nguyên âm trước, hàm mở vừa; lướt lên gần /ɪ/ trong cùng một âm tiết.", mouthEN: "Start with a mid front vowel and glide towards /ɪ/ within one syllable.", cueVI: "Phần đầu nổi bật hơn; không đọc thành hai âm tiết tách rời.", cueEN: "Make the first part more prominent; do not split it into two syllables."),
    .init(symbol: "aɪ", group: .diphthongs, examples: ["my", "time"], contrast: ["hat", "height"], mouthVI: "Bắt đầu với hàm mở, lưỡi thấp; lướt lên phía trước gần /ɪ/.", mouthEN: "Start with an open jaw and low tongue, then glide up and forward towards /ɪ/.", cueVI: "Giữ chuyển động liền; không ngắt giữa hai phần.", cueEN: "Keep the glide continuous without a break between its parts."),
    .init(symbol: "ɔɪ", group: .diphthongs, examples: ["boy", "choice"], contrast: ["boy", "buy"], mouthVI: "Bắt đầu với môi tròn, lưỡi ở sau; lướt lên trước gần /ɪ/ và thả độ tròn môi.", mouthEN: "Start with rounded lips and a back vowel; glide forward towards /ɪ/ while relaxing the rounding.", cueVI: "Phân biệt boy – buy bằng chất âm ở điểm bắt đầu.", cueEN: "Distinguish boy from buy by the starting vowel quality."),
    .init(symbol: "əʊ", group: .diphthongs, examples: ["go", "home"], contrast: ["coat", "cot"], mouthVI: "Bắt đầu ở vùng giữa với môi thả lỏng; lướt lên và hơi lùi, môi tròn dần.", mouthEN: "Start centrally with relaxed lips; glide upwards and slightly back, gradually rounding the lips.", cueVI: "Đây là ký hiệu GOAT của UK; đừng giữ một âm /o/ phẳng xuyên suốt.", cueEN: "This is the UK GOAT notation; avoid holding one flat /o/ throughout."),
    .init(symbol: "aʊ", group: .diphthongs, examples: ["now", "mouth"], contrast: ["how", "high"], mouthVI: "Bắt đầu với hàm mở; lướt lưỡi lên phía sau và làm tròn môi dần.", mouthEN: "Start with an open jaw; glide the tongue upwards and back while gradually rounding the lips.", cueVI: "now có một âm tiết; không tách thành hai lần bật giọng.", cueEN: "Now has one syllable; do not make two separate voice onsets."),
    .init(symbol: "ɪə", group: .diphthongs, examples: ["near", "here"], contrast: ["near", "knee"], mouthVI: "Bắt đầu gần /ɪ/, rồi thả lưỡi về giữa gần /ə/.", mouthEN: "Start near /ɪ/, then relax the tongue towards central /ə/.", cueVI: "NEAR có nhiều biến thể UK, gồm cả nguyên âm đơn dài; không tự coi khác biến thể là sai.", cueEN: "NEAR varies across UK accents, including a long monophthong; a different variant is not automatically wrong."),
    .init(symbol: "eə", group: .diphthongs, examples: ["hair", "care"], contrast: ["hair", "here"], mouthVI: "Bắt đầu với nguyên âm trước mở vừa, rồi thả về giữa. Nhiều người UK giữ âm /ɛː/ thay vì lướt rõ.", mouthEN: "Start with a mid-open front vowel and relax towards the centre. Many UK speakers use steady /ɛː/ instead.", cueVI: "SQUARE có thể viết /eə/, /ɛə/ hoặc /ɛː/ tùy hệ phiên âm. Không thêm /r/ cuối từ đứng riêng.", cueEN: "SQUARE may be written /eə/, /ɛə/ or /ɛː/. Do not add final /r/ in an isolated non-rhotic word."),
    .init(symbol: "ʊə", group: .diphthongs, examples: ["cure", "tour"], contrast: ["cure", "tour"], mouthVI: "Bắt đầu gần /ʊ/, môi tròn nhẹ, rồi thả lỏng về giữa /ə/.", mouthEN: "Start near /ʊ/ with loosely rounded lips, then relax towards central /ə/.", cueVI: "Âm CURE thay đổi nhiều; tour có thể dùng /ɔː/. Nghe mẫu UK của bài, không ép mọi người dùng /ʊə/.", cueEN: "CURE varies considerably; tour may use /ɔː/. Follow the lesson's UK reference rather than forcing /ʊə/ everywhere."),
    .init(symbol: "p", group: .consonants, examples: ["pen", "apple"], contrast: ["pat", "bat"], mouthVI: "Khép hai môi để chặn hơi rồi mở ra. Dây thanh không rung trong phần tắc.", mouthEN: "Close both lips to stop the air, then release. The closure is voiceless.", cueVI: "Đầu âm tiết nhấn thường có hơi bật; sau /s/ thì ít hơi hơn. Không thêm “pờ” ở cuối.", cueEN: "Usually aspirated at the start of a stressed syllable, less so after /s/. Do not add a final schwa."),
    .init(symbol: "b", group: .consonants, examples: ["book", "rabbit"], contrast: ["pat", "bat"], mouthVI: "Khép rồi mở hai môi; dùng ít hơi bật hơn /p/, với thanh quản chuẩn bị rung.", mouthEN: "Close and release both lips with less aspiration than /p/ and voicing readiness.", cueVI: "Âm cuối có thể mất một phần rung; đừng thêm nguyên âm sau /b/.", cueEN: "Final /b/ can be partly devoiced; do not append a vowel."),
    .init(symbol: "t", group: .consonants, examples: ["tea", "water"], contrast: ["tie", "die"], mouthVI: "Đầu lưỡi chạm gờ lợi ngay sau răng trên, chặn hơi rồi nhả.", mouthEN: "Touch the tongue tip to the ridge behind the upper teeth, stop the air, then release.", cueVI: "Không thêm “tờ” ở cuối. /t/ UK có thể không bật rõ hoặc thành âm tắc thanh hầu tùy vị trí.", cueEN: "Do not add a final schwa. UK /t/ may be unreleased or glottal depending on context."),
    .init(symbol: "d", group: .consonants, examples: ["day", "ladder"], contrast: ["tie", "die"], mouthVI: "Đầu lưỡi chạm gờ lợi như /t/; nhả với ít hơi bật và có xu hướng rung thanh.", mouthEN: "Use the alveolar closure of /t/, with less aspiration and a tendency towards voicing.", cueVI: "Giữ /d/ cuối mà không thêm nguyên âm; không bắt buộc rung mạnh suốt phần tắc.", cueEN: "Keep final /d/ without an added vowel; strong voicing throughout the closure is not required."),
    .init(symbol: "k", group: .consonants, examples: ["key", "back"], contrast: ["coat", "goat"], mouthVI: "Nâng phần sau lưỡi chạm vòm mềm, chặn hơi rồi nhả; không rung thanh.", mouthEN: "Raise the back of the tongue against the soft palate, stop the air and release without voicing.", cueVI: "Không dùng đầu lưỡi; âm cuối không cần thêm “cờ”.", cueEN: "Use the back rather than the tip of the tongue; do not add a final schwa."),
    .init(symbol: "ɡ", group: .consonants, examples: ["go", "bag"], contrast: ["coat", "goat"], mouthVI: "Phần sau lưỡi chặn hơi ở vòm mềm như /k/, nhả với ít hơi bật hơn.", mouthEN: "Use a velar closure like /k/, releasing with less aspiration.", cueVI: "Đừng đổi bag thành back; âm cuối có thể chỉ rung một phần.", cueEN: "Distinguish bag from back; final voicing may be partial."),
    .init(symbol: "f", group: .consonants, examples: ["fan", "coffee"], contrast: ["fan", "van"], mouthVI: "Răng trên chạm nhẹ môi dưới; thổi hơi liên tục qua khe hẹp, không rung thanh.", mouthEN: "Rest the upper teeth lightly against the lower lip; pass continuous air without voicing.", cueVI: "Không khép cả hai môi như /p/; giữ luồng hơi thay vì bật một lần.", cueEN: "Do not close both lips as for /p/; sustain the airflow rather than making a burst."),
    .init(symbol: "v", group: .consonants, examples: ["van", "seven"], contrast: ["fan", "van"], mouthVI: "Răng trên chạm nhẹ môi dưới như /f/, đồng thời tạo rung thanh.", mouthEN: "Use the lip–teeth position of /f/ while adding voicing.", cueVI: "Sờ nhẹ cổ để cảm nhận rung khi kéo âm; đừng thay bằng /w/ với hai môi tròn.", cueEN: "Feel voicing gently at the throat when sustaining it; avoid replacing it with rounded-lip /w/."),
    .init(symbol: "θ", group: .consonants, examples: ["think", "bath"], contrast: ["thin", "tin"], mouthVI: "Đặt đầu lưỡi sát hoặc hơi giữa hai hàm răng; cho hơi đi qua liên tục, không rung thanh.", mouthEN: "Place the tongue tip at or slightly between the teeth; let air flow continuously without voicing.", cueVI: "Đừng chặn hơi như /t/ hoặc rít thành /s/; thử thin – tin.", cueEN: "Avoid the complete closure of /t/ or the hiss of /s/; compare thin and tin."),
    .init(symbol: "ð", group: .consonants, examples: ["this", "mother"], contrast: ["then", "den"], mouthVI: "Đầu lưỡi sát răng như /θ/; thêm rung thanh khi hơi đi qua khe.", mouthEN: "Use the dental position of /θ/ and add voicing through the narrow gap.", cueVI: "Không chặn luồng hơi thành /d/; trong câu âm này thường nhẹ.", cueEN: "Avoid stopping the air as for /d/; this sound is often weak in connected speech."),
    .init(symbol: "s", group: .consonants, examples: ["see", "lesson"], contrast: ["sip", "zip"], mouthVI: "Đưa lưỡi gần gờ lợi, tạo rãnh hẹp cho hơi rít; không rung thanh.", mouthEN: "Bring the tongue close to the alveolar ridge, leaving a narrow groove for voiceless air.", cueVI: "Giữ đầu lưỡi không bịt kín đường hơi; phân biệt với /ʃ/ lùi hơn.", cueEN: "Do not block the airflow; distinguish it from the farther-back /ʃ/."),
    .init(symbol: "z", group: .consonants, examples: ["zoo", "rose"], contrast: ["sip", "zip"], mouthVI: "Giữ vị trí lưỡi của /s/ và thêm rung thanh.", mouthEN: "Use the tongue position of /s/ with added voicing.", cueVI: "Đừng bỏ âm /z/ cuối rose; có thể giảm rung ở cuối mà vẫn giữ ma sát.", cueEN: "Keep final /z/ in rose; some final devoicing is possible while friction remains."),
    .init(symbol: "ʃ", group: .consonants, examples: ["she", "fish"], contrast: ["sip", "ship"], mouthVI: "Đưa phần trước lưỡi gần vùng sau gờ lợi; môi hơi nhô, cho hơi ma sát không rung.", mouthEN: "Bring the tongue blade towards the area behind the alveolar ridge; slightly protrude the lips for voiceless friction.", cueVI: "Âm sâu hơn /s/; phân biệt sip – ship, không thêm âm /t/ trước nó.", cueEN: "It is farther back than /s/; compare sip and ship without adding a preceding /t/."),
    .init(symbol: "ʒ", group: .consonants, examples: ["vision", "measure"], contrast: ["pressure", "pleasure"], mouthVI: "Giữ vị trí /ʃ/ sau gờ lợi, nhưng thêm rung thanh.", mouthEN: "Use the post-alveolar position of /ʃ/ with voicing.", cueVI: "Giữ ma sát liền; không thêm phần tắc để biến thành /dʒ/.", cueEN: "Keep continuous friction; do not add a closure that turns it into /dʒ/."),
    .init(symbol: "h", group: .consonants, examples: ["hat", "behind"], contrast: ["hat", "at"], mouthVI: "Mở đường hơi qua thanh môn; miệng chuẩn bị sẵn tư thế nguyên âm tiếp theo.", mouthEN: "Let air pass through the open glottis, with the mouth already preparing the next vowel.", cueVI: "Thở nhẹ, không khạc ở cổ; tránh bỏ /h/ đầu hat.", cueEN: "Use gentle breath, not a harsh throat constriction; avoid dropping initial /h/ in hat."),
    .init(symbol: "tʃ", group: .consonants, examples: ["chair", "teacher"], contrast: ["ship", "chip"], mouthVI: "Chặn hơi bằng phần trước lưỡi sau gờ lợi rồi nhả ngay thành ma sát /ʃ/; không rung thanh.", mouthEN: "Make a post-alveolar closure, then release directly into /ʃ/-like voiceless friction.", cueVI: "Đây là một âm tắc-xát liền, không phải /t/ và /ʃ/ ở hai âm tiết.", cueEN: "Make one continuous affricate, not /t/ and /ʃ/ in separate syllables."),
    .init(symbol: "dʒ", group: .consonants, examples: ["job", "bridge"], contrast: ["cheap", "jeep"], mouthVI: "Chặn hơi sau gờ lợi rồi nhả thành ma sát /ʒ/, với xu hướng rung thanh.", mouthEN: "Make a post-alveolar closure and release into /ʒ/-like friction with voicing.", cueVI: "Đừng chỉ đọc /ʒ/ mà mất phần tắc đầu; so sánh cheap – jeep.", cueEN: "Keep the initial closure rather than using only /ʒ/; compare cheap and jeep."),
    .init(symbol: "m", group: .consonants, examples: ["man", "summer"], contrast: ["sum", "sun"], mouthVI: "Khép hai môi, hạ vòm mềm để hơi ra mũi; dây thanh rung.", mouthEN: "Close both lips and lower the soft palate so voiced air passes through the nose.", cueVI: "Giữ môi khép ở /m/ cuối; không thêm nguyên âm sau sum.", cueEN: "Keep the lips closed for final /m/; do not add a vowel after sum."),
    .init(symbol: "n", group: .consonants, examples: ["no", "dinner"], contrast: ["sin", "sing"], mouthVI: "Đầu lưỡi chạm gờ lợi; hơi có rung đi qua mũi.", mouthEN: "Touch the tongue tip to the alveolar ridge and let voiced air pass through the nose.", cueVI: "Đầu lưỡi làm việc, không phải phần sau lưỡi như /ŋ/.", cueEN: "Use the tongue tip rather than the back of the tongue used for /ŋ/."),
    .init(symbol: "ŋ", group: .consonants, examples: ["sing", "long"], contrast: ["sin", "sing"], mouthVI: "Phần sau lưỡi chạm vòm mềm; hơi có rung đi qua mũi.", mouthEN: "Raise the back of the tongue to the soft palate and let voiced air pass through the nose.", cueVI: "sing kết thúc bằng /ŋ/, không thêm /ɡ/ trừ khi phiên âm từ có ghi /ɡ/.", cueEN: "Sing ends in /ŋ/; do not append /ɡ/ unless the word's transcription includes it."),
    .init(symbol: "l", group: .consonants, examples: ["light", "feel"], contrast: ["light", "right"], mouthVI: "Đầu lưỡi chạm gờ lợi; hơi có rung đi qua hai bên lưỡi.", mouthEN: "Touch the tongue tip to the alveolar ridge and let voiced air pass around the sides.", cueVI: "Cuối âm tiết RP thường có dark L: phần sau lưỡi nâng hơn; không tự coi nó là âm sai.", cueEN: "RP syllable-final dark L often has a raised tongue back; that variant is not automatically an error."),
    .init(symbol: "ɹ", group: .consonants, examples: ["red", "around"], contrast: ["light", "right"], mouthVI: "Đưa đầu hoặc thân lưỡi gần vùng sau gờ lợi, không chạm và không rung đầu lưỡi.", mouthEN: "Bring the tongue tip or body towards the post-alveolar region without contact or a trill.", cueVI: "RP thường không có /r/ trước phụ âm hoặc cuối câu; linking r có thể xuất hiện trước nguyên âm.", cueEN: "RP usually lacks /r/ before a consonant or at phrase end; linking r may occur before a vowel."),
    .init(symbol: "j", group: .consonants, examples: ["yes", "yellow"], contrast: ["yet", "jet"], mouthVI: "Nâng lưỡi về phía vòm cứng, gần tư thế /i/, rồi lướt thẳng vào nguyên âm.", mouthEN: "Raise the tongue towards the hard palate, near /i/, then glide directly into the vowel.", cueVI: "Không thêm phần tắc-xát của /dʒ/; yes không bắt đầu như chữ j trong jet.", cueEN: "Do not add the closure and friction of /dʒ/; yes does not start like jet."),
    .init(symbol: "w", group: .consonants, examples: ["we", "away"], contrast: ["west", "vest"], mouthVI: "Tròn hai môi và nâng phần sau lưỡi; mở môi khi lướt vào nguyên âm.", mouthEN: "Round both lips and raise the tongue back; open the lips as you glide into the vowel.", cueVI: "Răng trên không chạm môi dưới như /v/; so sánh west – vest.", cueEN: "Keep the upper teeth off the lower lip, unlike /v/; compare west and vest."),
  ]
}
